# Generated by Django 5.1.1 on 2024-09-16 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('International_Code', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=11)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Code_vezarat_olom', models.CharField(max_length=20)),
                ('Work_experience', models.BooleanField(choices=[('True', 'بله'), ('False', 'خیر')], default=False)),
                ('Education', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Teacher', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Education_level', models.CharField(max_length=50)),
                ('Debt_status', models.CharField(choices=[('SUSPENDED', 'معلق شده'), ('PAID', 'پرداخت شده'), ('UNPAID', 'پرداخت نشده')], max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Student', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('Parent_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Number_of_children', models.IntegerField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Parent', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('Manager_Id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Manager', to='User.user')),
            ],
        ),
    ]
