# Generated by Django 5.0.6 on 2024-09-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='User.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Work_experience',
            field=models.BooleanField(choices=[('بله', 'True'), ('خیر', 'False')], default=False),
        ),
    ]
