# Generated by Django 5.0.6 on 2024-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_teacher_user_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Work_experience',
            field=models.BooleanField(choices=[('True', 'بله'), ('False', 'خیر')], default=False),
        ),
    ]
