# Generated by Django 5.0.6 on 2024-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_teacher_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Debt_status',
            field=models.CharField(choices=[('معلق شده', 'SUSPENDED'), ('پرداخت شده', 'PAID'), ('پرداخت نشده', 'UNPAID')], max_length=50),
        ),
    ]
