# Generated by Django 5.0.6 on 2024-09-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_student_debt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Debt_status',
            field=models.CharField(choices=[('SUSPENDED', 'معلق شده'), ('PAID', 'پرداخت شده'), ('UNPAID', 'پرداخت نشده')], max_length=50),
        ),
    ]
